"""update datetime to timezone aware

Revision ID: 730ca79a8f35
Revises: 002_medication_journey
Create Date: 2026-05-28 09:28:32.790590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '730ca79a8f35'
down_revision: Union[str, None] = '002_medication_journey'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('knowledge_base', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('medication_journey', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('medication_journey', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_medication_log_journey_id'), table_name='medication_log')
    op.drop_index(op.f('ix_medication_log_time_taken'), table_name='medication_log')
    op.drop_constraint(op.f('medication_log_journey_id_fkey'), 'medication_log', type_='foreignkey')
    op.create_foreign_key(None, 'medication_log', 'medication_journey', ['journey_id'], ['id'])
    op.drop_index(op.f('ix_log_entry_log_id'), table_name='medication_log_entry')
    op.drop_constraint(op.f('medication_log_entry_prescribed_dose_id_fkey'), 'medication_log_entry', type_='foreignkey')
    op.drop_constraint(op.f('medication_log_entry_log_id_fkey'), 'medication_log_entry', type_='foreignkey')
    op.create_foreign_key(None, 'medication_log_entry', 'medication_log', ['log_id'], ['id'])
    op.create_foreign_key(None, 'medication_log_entry', 'prescribed_dose', ['prescribed_dose_id'], ['id'])
    op.drop_index(op.f('ix_prescribed_dose_journey_id'), table_name='prescribed_dose')
    op.drop_constraint(op.f('prescribed_dose_journey_id_fkey'), 'prescribed_dose', type_='foreignkey')
    op.create_foreign_key(None, 'prescribed_dose', 'medication_journey', ['journey_id'], ['id'])
    op.alter_column('session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_user_achievement'), 'user_achievement', type_='unique')
    op.drop_constraint(op.f('user_achievement_achievement_id_fkey'), 'user_achievement', type_='foreignkey')
    op.create_foreign_key(None, 'user_achievement', 'achievement', ['achievement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_achievement', type_='foreignkey')
    op.create_foreign_key(op.f('user_achievement_achievement_id_fkey'), 'user_achievement', 'achievement', ['achievement_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_achievement'), 'user_achievement', ['user_id', 'achievement_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('session', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'prescribed_dose', type_='foreignkey')
    op.create_foreign_key(op.f('prescribed_dose_journey_id_fkey'), 'prescribed_dose', 'medication_journey', ['journey_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_prescribed_dose_journey_id'), 'prescribed_dose', ['journey_id'], unique=False)
    op.drop_constraint(None, 'medication_log_entry', type_='foreignkey')
    op.drop_constraint(None, 'medication_log_entry', type_='foreignkey')
    op.create_foreign_key(op.f('medication_log_entry_log_id_fkey'), 'medication_log_entry', 'medication_log', ['log_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('medication_log_entry_prescribed_dose_id_fkey'), 'medication_log_entry', 'prescribed_dose', ['prescribed_dose_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_log_entry_log_id'), 'medication_log_entry', ['log_id'], unique=False)
    op.drop_constraint(None, 'medication_log', type_='foreignkey')
    op.create_foreign_key(op.f('medication_log_journey_id_fkey'), 'medication_log', 'medication_journey', ['journey_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_medication_log_time_taken'), 'medication_log', ['time_taken'], unique=False)
    op.create_index(op.f('ix_medication_log_journey_id'), 'medication_log', ['journey_id'], unique=False)
    op.alter_column('medication_journey', 'end_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('medication_journey', 'start_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('knowledge_base', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('audit_log', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
